spring:
  application:
    name: sms-services

application:
  sayqal:
    url: ${sayqal_url}
    login: ${sayqal_login}
    password: ${sayqal_password}
  get-sms:
    url: ${getsms_url}
    login: ${getsms_login}
    password: ${getsms_password}
  eskiz:
    url: ${eskiz_url}
    email: ${eskiz_email}
    password: ${eskiz_password}